### ISSUE TITLE
Audioplayer tab transparency

### ISSUE THREAD

**Issue by danallan** [cs50/harvard.cs50.audioplayer#2]
It looks like audioplayer tabs may not contain the right opacity level, such that they are somewhat transparent. Here is how an audioplayer tab appears on my IDE:
![screen shot 2016-07-20 at 10 51 16 am](https://cloud.githubusercontent.com/assets/877725/16990988/120dd9f4-4e68-11e6-9b65-7eef9529ea74.png)

Here is a corresponding text tab:
![screen shot 2016-07-20 at 10 52 51 am](https://cloud.githubusercontent.com/assets/877725/16991010/2230edd0-4e68-11e6-8bf9-48a9a7725ffe.png)

Any ideas, @kzidane?

**Comment by kzidane** [comment]
@danallan thank you for reporting! fixed #3!
